pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = credentials('github-creds')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: "${GITHUB_CREDENTIALS}",
                    url: 'https://github.com/<your-username>/alx-backend-python.git'
            }
        }

        stage('Set up Python') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest --junitxml=report.xml --cov=messaging_app > result.log || true
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
